# Generated by Django 5.1.3 on 2024-11-19 12:13

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=catalog.models.product_image_upload_path)),
            ],
        ),
    ]
