# Generated by Django 5.1.3 on 2024-11-29 16:56

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default_product', upload_to=catalog.models.product_image_upload_path),
        ),
    ]
