# Generated by Django 5.1.3 on 2024-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_name_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
